---
title: "Classification Lab"
author: "Zhengting (Johnathan) He"
date: "2022/2/5"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
require(ISLR)
```


# The Stock Market Data


```{r}
names(Smarket)
```


```{r}
dim(Smarket)
```


```{r}
summary(Smarket)
```


```{r}
cor(Smarket[, -9])
```


```{r}
attach(Smarket)
plot(Smarket$Year, Smarket$Volumn)
```


# Logistic Regression


```{r}
glm.fits <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume,
                data = Smarket, family = binomial)
summary(glm.fits)
```


```{r}
coef(glm.fits)
```


```{r}
summary(glm.fits)$coef
```


```{r}
summary(glm.fits)$coef[, 4]
```


```{r}
glm.probs <- predict(glm.fits, type = "response")
glm.probs[1:10]
```


```{r}
contrasts(Direction)
```


```{r}
glm.pred <- rep("Down", 1250)
glm.pred[glm.probs > 0.5] <- "Up"
```


```{r}
table(glm.pred, Direction)
```


```{r}
(507+145)/1250
```


```{r}
mean(glm.pred == Direction)
```


```{r}
train <- (Year < 2005)
Smarket.2005 <- Smarket[!train, ]
dim(Smarket.2005)
```


```{r}
Direction.2005 <- Direction[!train]
```


```{r}
glm.fits <- glm(Direction ~ Lag1 + Lag2 + Lag3 + Lag4 + Lag5 + Volume,
                data = Smarket, family = binomial, subset = train)
glm.probs <- predict(glm.fits, Smarket.2005, type = "response")
```


```{r}
glm.pred <- rep("Down", 252)
glm.pred[glm.probs > 0.5] <- "Up"
table(glm.pred, Direction.2005)
```


```{r}
mean(glm.pred == Direction.2005)
```


```{r}
mean(glm.pred != Direction.2005)
```


```{r}
glm.fits <- glm(Direction ~ Lag1 + Lag2,
                data = Smarket, family = binomial, subset = train)
glm.probs <- predict(glm.fits, Smarket.2005, type = "response")
glm.pred <- rep("Down", 252)
glm.pred[glm.probs > 0.5] <- "Up"
table(glm.pred, Direction.2005)
```


```{r}
mean(glm.pred == Direction.2005)
```


```{r}
106/(106+76)
```


```{r}
predict(glm.fits, newdata = data.frame(Lag1 = c(1.2, 1.5), Lag2 = c(1.1, -0.8)),
        type = "response")
```


# Linear Discriminant Analysis


```{r}
require(MASS)
lda.fit <- lda(Direction ~ Lag1 + Lag2, data = Smarket, subset = train)
lda.fit
```


```{r}
plot(lda.fit)
```


```{r}
lda.pred <- predict(lda.fit, Smarket.2005)
names(lda.pred)
```


```{r}
lda.class <- lda.pred$class
table(lda.class, Direction.2005)
```


```{r}
mean(lda.class == Direction.2005)
```


```{r}
sum(lda.pred$posterior[, 1] >= 0.5)
sum(lda.pred$posterior[, 1] < 0.5)
```


```{r}
lda.pred$posterior[1:20,1]
```


```{r}
lda.class[1:20]
```


```{r}
sum(lda.pred$posterior[, 1] > 0.9)
```


# Quadratic Discriminant Analysis


```{r}
qda.fit <- qda(Direction ~ Lag1 + Lag2, data = Smarket, subset = train)
qda.fit
```


```{r}
qda.class <- predict(qda.fit, Smarket.2005)$class
table(qda.class, Direction.2005)
```


```{r}
mean(qda.class == Direction.2005)
```


# K-Nearest Neighbors


```{r}
require(class)
train.X <- cbind(Lag1, Lag2)[train, ]
test.X <- cbind(Lag1, Lag2)[!train, ]
train.Direction <- Direction[train]
```


```{r}
set.seed(1)
knn.pred <- knn(train.X, test.X, train.Direction, k = 1)
table(knn.pred, Direction.2005)
```


```{r}
(83+43)/252
```


```{r}
set.seed(1)
knn.pred <- knn(train.X, test.X, train.Direction, k = 3)
table(knn.pred, Direction.2005)
```


```{r}
mean(knn.pred == Direction.2005)
```


# An Application to Caravan Insurance Data


```{r}
dim(Caravan)
```


```{r}
attach(Caravan)
summary(Purchase)
```


```{r}
348/5822
```


```{r}
standardized.X = scale(Caravan[, -86])
var(Caravan[, 1])
var(Caravan[, 2])
var(standardized.X[, 1])
var(standardized.X[, 2])
```


```{r}
test <- 1:1000
train.X <- standardized.X[-test, ]
test.X <- standardized.X[test, ]
train.Y <- Purchase[-test]
test.Y <- Purchase[test]
set.seed(1)
knn.pred <- knn(train.X, test.X, train.Y, k = 1)
mean(test.Y != knn.pred)
mean(test.Y != "No")
```


```{r}
table(knn.pred, test.Y)
```


```{r}
9/(68+9)
```


```{r}
set.seed(1)
knn.pred <- knn(train.X, test.X, train.Y, k = 3)
table(knn.pred, test.Y)
```


```{r}
5/(20+5)
```


```{r}
set.seed(1)
knn.pred <- knn(train.X, test.X, train.Y, k = 5)
table(knn.pred, test.Y)
```


```{r}
4/(11+4)
```


```{r}
glm.fits <- glm(Purchase ~ ., data = Caravan, family = binomial, subset = -test)
glm.probs <- predict(glm.fits, Caravan[test, ], type = "response")
glm.pred <- rep("No", 1000)
glm.pred[glm.probs > 0.5] <- "Yes"
table(glm.pred, test.Y)
```


```{r}
glm.pred <- rep("No", 1000)
glm.pred[glm.probs > 0.25] <- "Yes"
table(glm.pred, test.Y)
```


```{r}
11/(22+11)
```

